export interface TalentProfile {
  id: string
  name: string
  roleSlug: string
  seniority: 'Mid' | 'Senior' | 'Lead'
  location: string
  availability: 'Active' | 'Available Soon' | 'Engaged'
  score: number
  avatarInitials: string
  verified: boolean
  skills: string[]
  yearsExperience: number
  dailyRate: number
  bio: string
}

export const TALENT_PROFILES: TalentProfile[] = [
  {
    id: 't-001',
    name: 'Sarah Chen',
    roleSlug: 'integration-engineer',
    seniority: 'Senior',
    location: 'Sydney',
    availability: 'Active',
    score: 94,
    avatarInitials: 'SC',
    verified: true,
    skills: ['Claude API', 'MCP Servers', 'TypeScript', 'Python', 'REST APIs'],
    yearsExperience: 8,
    dailyRate: 1100,
    bio: 'Specialist in building production Claude API integrations and MCP server deployments. Led integration projects for 3 ASX-100 companies.',
  },
  {
    id: 't-002',
    name: 'James Wu',
    roleSlug: 'solutions-architect',
    seniority: 'Lead',
    location: 'Melbourne',
    availability: 'Active',
    score: 91,
    avatarInitials: 'JW',
    verified: true,
    skills: ['Enterprise Architecture', 'Claude Integration', 'AWS', 'System Design', 'Stakeholder Management'],
    yearsExperience: 12,
    dailyRate: 1600,
    bio: 'Enterprise architect specialising in Anthropic ecosystem design. Delivered AI transformation programs for financial services and government clients.',
  },
  {
    id: 't-003',
    name: 'Priya Sharma',
    roleSlug: 'data-analytics-engineer',
    seniority: 'Senior',
    location: 'Brisbane',
    availability: 'Available Soon',
    score: 87,
    avatarInitials: 'PS',
    verified: true,
    skills: ['Data Pipelines', 'Claude Analytics', 'Python', 'SQL', 'dbt'],
    yearsExperience: 6,
    dailyRate: 1000,
    bio: 'Data engineer connecting enterprise data lakes to Claude for automated insight generation. Strong background in healthcare and retail analytics.',
  },
  {
    id: 't-004',
    name: 'Michael Torres',
    roleSlug: 'project-program-manager',
    seniority: 'Senior',
    location: 'Sydney',
    availability: 'Active',
    score: 92,
    avatarInitials: 'MT',
    verified: true,
    skills: ['Program Delivery', 'Agile', 'Stakeholder Management', 'Risk Management', 'AI Projects'],
    yearsExperience: 10,
    dailyRate: 1200,
    bio: 'Program manager with a track record of delivering complex AI integration projects on time and within budget. PMP and SAFe certified.',
  },
  {
    id: 't-005',
    name: 'Emma Richardson',
    roleSlug: 'change-adoption-manager',
    seniority: 'Lead',
    location: 'Melbourne',
    availability: 'Active',
    score: 89,
    avatarInitials: 'ER',
    verified: true,
    skills: ['Change Management', 'AI Adoption', 'Workshop Facilitation', 'Training Design', 'Prosci'],
    yearsExperience: 9,
    dailyRate: 1100,
    bio: 'Change leader driving enterprise AI adoption across organisations. Designed adoption frameworks for 5+ large-scale Claude deployments.',
  },
  {
    id: 't-006',
    name: 'David Kumar',
    roleSlug: 'integration-engineer',
    seniority: 'Mid',
    location: 'Perth',
    availability: 'Available Soon',
    score: 85,
    avatarInitials: 'DK',
    verified: true,
    skills: ['Claude API', 'Node.js', 'React', 'REST APIs', 'Testing'],
    yearsExperience: 4,
    dailyRate: 900,
    bio: 'Full-stack developer transitioning into dedicated Claude integration work. Built internal tools powered by Claude for mining sector clients.',
  },
  {
    id: 't-007',
    name: 'Lisa Zhang',
    roleSlug: 'cowork-config-specialist',
    seniority: 'Senior',
    location: 'Sydney',
    availability: 'Active',
    score: 88,
    avatarInitials: 'LZ',
    verified: true,
    skills: ['Cowork Setup', 'Plugin Configuration', 'User Training', 'Documentation', 'Troubleshooting'],
    yearsExperience: 5,
    dailyRate: 850,
    bio: 'Hands-on Cowork configuration specialist. Completed 20+ enterprise Cowork deployments with 95% user satisfaction scores.',
  },
  {
    id: 't-008',
    name: 'Alex Nakamura',
    roleSlug: 'security-governance',
    seniority: 'Lead',
    location: 'Canberra',
    availability: 'Engaged',
    score: 93,
    avatarInitials: 'AN',
    verified: true,
    skills: ['AI Governance', 'Cybersecurity', 'Compliance', 'Risk Assessment', 'IRAP'],
    yearsExperience: 14,
    dailyRate: 1500,
    bio: 'AI governance and cybersecurity lead with deep government sector experience. Developed AI risk frameworks aligned with Australian AI Ethics Principles.',
  },
  {
    id: 't-009',
    name: 'Sophie Martin',
    roleSlug: 'ai-trainer-prompt-engineer',
    seniority: 'Senior',
    location: 'Adelaide',
    availability: 'Active',
    score: 86,
    avatarInitials: 'SM',
    verified: true,
    skills: ['Prompt Engineering', 'Training Design', 'Claude Optimisation', 'Content Strategy', 'UX Writing'],
    yearsExperience: 5,
    dailyRate: 800,
    bio: 'Prompt engineer and AI trainer helping teams get the most from Claude. Created training curricula adopted by 3 major universities.',
  },
  {
    id: 't-010',
    name: 'Ryan O\'Brien',
    roleSlug: 'enterprise-integration-dev',
    seniority: 'Senior',
    location: 'Sydney',
    availability: 'Active',
    score: 90,
    avatarInitials: 'RO',
    verified: true,
    skills: ['Enterprise Integration', 'SAP', 'Salesforce', 'Claude API', 'Middleware'],
    yearsExperience: 11,
    dailyRate: 1200,
    bio: 'Enterprise integration developer connecting legacy systems to Claude-powered workflows. Deep expertise in SAP and Salesforce ecosystems.',
  },
]

export function getProfileById(id: string): TalentProfile | undefined {
  return TALENT_PROFILES.find((p) => p.id === id)
}
